ALTER TABLE infra_members
  ADD COLUMN IF NOT EXISTS account_type VARCHAR(32) NOT NULL DEFAULT 'business',
  ADD COLUMN IF NOT EXISTS dayfi_tag VARCHAR(64),
  ADD COLUMN IF NOT EXISTS phone VARCHAR(32),
  ADD COLUMN IF NOT EXISTS date_of_birth DATE,
  ADD COLUMN IF NOT EXISTS country VARCHAR(8),
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS bvn VARCHAR(16),
  ADD COLUMN IF NOT EXISTS kyc_level INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS personal_onboarding_complete BOOLEAN NOT NULL DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS infra_members_dayfi_tag_uidx
  ON infra_members (LOWER(dayfi_tag))
  WHERE dayfi_tag IS NOT NULL AND dayfi_tag <> '';
